---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmap-ip.fullname" . }}
  labels:
{{ include "nmap-ip.labels" . | indent 4 }}
{{ include "cenm.labels" . | indent 4 }}
spec:
# we need Local policy and healthCheckNodePort set to get rid of logs pollution
{{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
{{- end }}
  externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nmapb
    app.kubernetes.io/instance: {{ .Values.prefix }}-nmapb
