---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-nmap-conf
  labels:
    {{ include "nmap.labels" . | nindent 4 }}
data:
  run.sh: |+
    {{ tpl (.Files.Get "files/run.sh") . | nindent 4 }}

  getZoneToken.sh: |+
    {{ tpl (.Files.Get "files/getZoneToken.sh") . | nindent 4 }}

  networkmap.conf: |+
    {{ tpl (.Files.Get "files/networkmap.conf") . | nindent 4 }}

  create-network-parameters-file.sh: |+
    {{ tpl (.Files.Get "files/create-network-parameters-file.sh") . | nindent 4 }}
  
  setupAuth.sh: |+
{{ tpl (.Files.Get "files/setupAuth.sh") . | indent 4 }}

{{- tpl ((.Files.Glob "files/role-assignments/*.json").AsConfig) . | nindent 2 }}

