
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-nmap-etc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNmapEtc }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-nmap-logs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNmapLogs }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}-nmap-h2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumeSizeNmapH2 }}

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: {{ .Values.prefix }}-nmap-conf
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: {{ .Values.storageClass }}
#  resources:
#    requests:
#      storage: {{ .Values.volumeSizeNmapH2 }}