---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmap.fullname" . }}-internal
  labels:
    {{- include "nmap.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.serviceInternal.port }}
      targetPort: {{ .Values.serviceInternal.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.adminListener.port }}
      targetPort: {{ .Values.adminListener.port }}
      protocol: TCP
      name: adminlistener
  selector:
    # app.kubernetes.io/name: {{ include "nmap.name" . }}
    {{- include "nmap.selectorLabels" . | nindent 4 }}

  